name: Daily Solana Airdrop

on:
  schedule:
    - cron: '0 */9 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  request-sol:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v1.18.25/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Verify Solana installation
        run: solana --version

      - name: Request SOL via airdrop
        run: bash solana_airdrop.sh

      - name: Create status log
        if: always()
        run: |
          mkdir -p logs
          echo "Last run: $(date)" > logs/last_run.txt
          echo "Status: ${{ job.status }}" >> logs/last_run.txt
          echo "Wallet: 9cV3D54tgGDxwXZeKUPt634diseVQETo56HoHejy6tAA" >> logs/last_run.txt
          echo "Current Balance: $(solana balance 9cV3D54tgGDxwXZeKUPt634diseVQETo56HoHejy6tAA --url https://api.devnet.solana.com)" >> logs/last_run.txt

      - name: Commit and push status log
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update airdrop request log"
          file_pattern: "logs/last_run.txt"
