name: Daily Solana Airdrop

on:
  schedule:
    - cron: '0 */9 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  request-sol:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v1.18.25/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Verify Solana installation
        run: solana --version

      - name: Request SOL via airdrop
        run: bash solana_airdrop.sh
